/**
 * Azure Marketplace image catalog for "Fresh VM" creation.
 * Each entry maps to a standard Azure Marketplace image that can be
 * deployed without a pre-built custom template.
 */
const MARKETPLACE_IMAGES = {
  'ubuntu-22': {
    label: 'Ubuntu 22.04 LTS',
    os: 'Linux',
    publisher: 'Canonical',
    offer: '0001-com-ubuntu-server-jammy',
    sku: '22_04-lts-gen2',
    version: 'latest',
    planRequired: false,
    licence: 'none',
    securityType: 'TrustedLaunch',
    icon: 'ubuntu',
    defaultVmSize: 'Standard_D2ls_v5',
    defaultDiskGB: 30,
  },
  'ubuntu-24': {
    label: 'Ubuntu 24.04 LTS',
    os: 'Linux',
    publisher: 'Canonical',
    offer: 'ubuntu-24_04-lts',
    sku: 'server',
    version: 'latest',
    planRequired: false,
    licence: 'none',
    securityType: 'TrustedLaunch',
    icon: 'ubuntu',
    defaultVmSize: 'Standard_D2ls_v5',
    defaultDiskGB: 30,
  },
  'windows-server-2019': {
    label: 'Windows Server 2019',
    os: 'Windows',
    publisher: 'MicrosoftWindowsServer',
    offer: 'WindowsServer',
    sku: '2019-datacenter-gensecond',
    version: 'latest',
    planRequired: false,
    licence: 'Windows_Server',
    securityType: 'TrustedLaunch',
    icon: 'windows',
    defaultVmSize: 'Standard_D2ls_v5',
    defaultDiskGB: 127,
  },
  'windows-server-2022': {
    label: 'Windows Server 2022',
    os: 'Windows',
    publisher: 'MicrosoftWindowsServer',
    offer: 'WindowsServer',
    sku: '2022-datacenter-g2',
    version: 'latest',
    planRequired: false,
    licence: 'Windows_Server',
    securityType: 'TrustedLaunch',
    icon: 'windows',
    defaultVmSize: 'Standard_D2ls_v5',
    defaultDiskGB: 127,
  },
  'windows-10-pro': {
    label: 'Windows 10 Pro',
    os: 'Windows',
    publisher: 'MicrosoftWindowsDesktop',
    offer: 'Windows-10',
    sku: 'win10-22h2-pro-g2',
    version: 'latest',
    planRequired: false,
    licence: 'Windows_Client',
    securityType: 'TrustedLaunch',
    icon: 'windows',
    defaultVmSize: 'Standard_D2ls_v5',
    defaultDiskGB: 127,
  },
  'rocky-linux-9': {
    label: 'Rocky Linux 9',
    os: 'Linux',
    publisher: 'resf',
    offer: 'rockylinux-x86_64',
    sku: '9-base',
    version: 'latest',
    planRequired: true,
    planPublisher: 'resf',
    product: 'rockylinux-x86_64',
    planName: '9-base',
    licence: 'none',
    securityType: 'TrustedLaunch',
    icon: 'rocky',
    defaultVmSize: 'Standard_D2ls_v5',
    defaultDiskGB: 10,
  },
  'rhel-9': {
    label: 'Red Hat Enterprise Linux 9',
    os: 'Linux',
    publisher: 'RedHat',
    offer: 'RHEL',
    sku: '9_4',
    version: 'latest',
    planRequired: false,
    licence: 'RHEL_BYOS',
    securityType: 'TrustedLaunch',
    icon: 'rhel',
    defaultVmSize: 'Standard_D2ls_v5',
    defaultDiskGB: 64,
  },
};

module.exports = MARKETPLACE_IMAGES;
